/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDiscordGatewayRouteImport } from './routes/api/public/discord/gateway'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'
import { Route as ApiPublicDiscordRtpRouteImport } from './routes/api/public/discord/rtp'
import { Route as ApiPublicDiscordScanDepositsRouteImport } from './routes/api/public/discord/scan-deposits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordGatewayRoute = ApiPublicDiscordGatewayRouteImport.update({
  id: '/api/public/discord/gateway',
  path: '/api/public/discord/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordRtpRoute = ApiPublicDiscordRtpRouteImport.update({
  id: '/api/public/discord/rtp',
  path: '/api/public/discord/rtp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordScanDepositsRoute =
  ApiPublicDiscordScanDepositsRouteImport.update({
    id: '/api/public/discord/scan-deposits',
    path: '/api/public/discord/scan-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/discord/gateway': typeof ApiPublicDiscordGatewayRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/rtp': typeof ApiPublicDiscordRtpRoute
  '/api/public/discord/scan-deposits': typeof ApiPublicDiscordScanDepositsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/discord/gateway': typeof ApiPublicDiscordGatewayRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/rtp': typeof ApiPublicDiscordRtpRoute
  '/api/public/discord/scan-deposits': typeof ApiPublicDiscordScanDepositsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/discord/gateway': typeof ApiPublicDiscordGatewayRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/rtp': typeof ApiPublicDiscordRtpRoute
  '/api/public/discord/scan-deposits': typeof ApiPublicDiscordScanDepositsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/discord/gateway'
    | '/api/public/discord/interactions'
    | '/api/public/discord/rtp'
    | '/api/public/discord/scan-deposits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/discord/gateway'
    | '/api/public/discord/interactions'
    | '/api/public/discord/rtp'
    | '/api/public/discord/scan-deposits'
  id:
    | '__root__'
    | '/'
    | '/api/public/discord/gateway'
    | '/api/public/discord/interactions'
    | '/api/public/discord/rtp'
    | '/api/public/discord/scan-deposits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDiscordGatewayRoute: typeof ApiPublicDiscordGatewayRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
  ApiPublicDiscordRtpRoute: typeof ApiPublicDiscordRtpRoute
  ApiPublicDiscordScanDepositsRoute: typeof ApiPublicDiscordScanDepositsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/gateway': {
      id: '/api/public/discord/gateway'
      path: '/api/public/discord/gateway'
      fullPath: '/api/public/discord/gateway'
      preLoaderRoute: typeof ApiPublicDiscordGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/rtp': {
      id: '/api/public/discord/rtp'
      path: '/api/public/discord/rtp'
      fullPath: '/api/public/discord/rtp'
      preLoaderRoute: typeof ApiPublicDiscordRtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/scan-deposits': {
      id: '/api/public/discord/scan-deposits'
      path: '/api/public/discord/scan-deposits'
      fullPath: '/api/public/discord/scan-deposits'
      preLoaderRoute: typeof ApiPublicDiscordScanDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDiscordGatewayRoute: ApiPublicDiscordGatewayRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
  ApiPublicDiscordRtpRoute: ApiPublicDiscordRtpRoute,
  ApiPublicDiscordScanDepositsRoute: ApiPublicDiscordScanDepositsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
